/*
 * definition of menuconfig macro
 */

#define LCD_OFF_TIME_VBUS CONFIG_LCD_OFF_TIME_VBUS
#define LCD_OFF_TIME_BATT CONFIG_LCD_OFF_TIME_BATT

#ifdef CONFIG_AXP192_CHG_VOLTAGE_V41
#define AXP192_CHG_VOLTAGE_V41 1
#endif
#ifdef CONFIG_AXP192_CHG_VOLTAGE_V415
#define AXP192_CHG_VOLTAGE_V415 1
#endif
#ifdef CONFIG_AXP192_CHG_VOLTAGE_V42
#define AXP192_CHG_VOLTAGE_V42 1
#endif

#ifdef CONFIG_AXP192_CHG_10PERCENT
#define AXP192_CHG_10PERCENT 1
#endif
#ifdef CONFIG_AXP192_CHG_15PERCENT
#define AXP192_CHG_15PERCENT 1
#endif

#define TIME_ZONE CONFIG_TIME_ZONE

#ifdef CONFIG_BATTERY_INFO
#define BATTERY_INFO 1
#endif
